name: Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run make
        run: make
      - name: Run make check
        run: make check
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }} -B
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password

#      - name: Configure git
#        run: |
#          git config --global user.name "${GITHUB_ACTOR}"
#          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#      - name: Prepare release
#        run: mvn --batch-mode release:prepare
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Perform release
#        run: mvn --batch-mode release:perform
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Set Version
#        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }} -B
#      - name: Install
#        run: mvn install
#      - name: Deploy
#        run: mvn -s .github/workflows/m2/settings.xml deploy -DskipTests -B -X
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Figure out the project version from pom.xml
#        run: |
#          # Go back to the commit before the SNAPSHOT
#          git reset --hard HEAD~1
#          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"
#      - name: Create Release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: apm-proto-${{ env.VERSION }}
#          release_name: apm-proto ${{ env.VERSION }}
#          draft: false
#          prerelease: false
