name: Release
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: version

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run make
        run: make
      - name: Run make check
        run: make check
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Version
        run: mvn versions:set -DnewVersion=${{ github.event.inputs.version }} -B
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
#      - name: Create Release
#        uses: actions/create-release@latest
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.event.inputs.version }}
#          release_name: apm-proto ${{ github.event.inputs.version }}
#          draft: false
#          prerelease: false
